### ISSUE TITLE
doing pagination

### ISSUE THREAD

**Issue by Fshamri** [fguillot/picoDb#12]
lets say i want to do pagination, i.e. user insert page number and offset

using sqlite i will use the following query to get

    SELECT count (*) FROM (select * from items LIMIT  $per_page OFFSET $offset)

 php:
  
    $current page = $_GET['page'] ;
    $per_page=10;
    $offset = ($_GET['page'] * $perPage - $perPage);
    $pages = ceil($total / $perPage);

so, i will get json output for example:

    {
      current page:2
      pages: 50

how can i atchive the same query using your library?

**Comment by fguillot** [comment]
For the pagination, you just need to play with the method `offset()` and `limit()`: https://github.com/fguillot/picoDb#limit-and-offset

**Comment by Fshamri** [comment]
thanks
