### ISSUE TITLE
sqlite: quotation bug/sideeffect

### ISSUE THREAD

**Issue by mkresin** [fguillot/picoDb#3]
The following sqlite table 'toto'

|Number|column1|LastName|Points|
|---|---|---|---|
|1|Eve|Jackson|94|
|2|John|Doe|80|
|3|Adam|Johnson|67|
|4|Jill|Smith|50|

and the following example code using a non-existent column name:

```php
 $db->table('toto')->columns('column1', 'column2')->findAll();
```

returns the following result set:

```
Array
(
    [0] => Array
        (
            [column1] => Eve
            ["column2"] => column2
        )

    [1] => Array
        (
            [column1] => John
            ["column2"] => column2
        )

    [2] => Array
        (
            [column1] => Adam
            ["column2"] => column2
        )

    [3] => Array
        (
            [column1] => Jill
            ["column2"] => column2
        )
		
)
```

Where I'm expecting a Runtime Exception because of the non-existent column. The following quoting variations resulting in a "no such column error":

- ```SELECT [column1], [column2] FROM "toto" ``` (MS Access compatibility)
- ```SELECT `column1`, `column2` FROM "toto" ``` (MySQL compatibility)
- ```SELECT "toto"."column1", "todo"."column2" FROM "toto" ```

**Comment by fguillot** [comment]
I added the table name to the column list, so sqlite returns an error now.

Thanks.
